# Generated by Django 4.0.6 on 2022-07-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindhudurga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myclass',
            table='my_class',
        ),
    ]
